clone:
    path: github.com/vmware/docker-volume-vsphere
    tags: true

build:

  serialize:
    image: cnastorage/vibauthor-and-go:0.9
    environment:
      - DRONE_TOKEN=$$DRONE_TOKEN
      - DRONE_SERVER=$$DRONE_SERVER
      - TEST_URL_ARRAY=$$TEST_URL_ARRAY
      - GOVC_USERNAME=$$CI_BASE_VMWARE_ESX_USER
      - GOVC_PASSWORD=$$CI_BASE_VMWARE_ESX_PASS
      - GOVC_INSECURE=1
      - GOVC_URL=$$CI_BASE_ESX_IP
      - TEST_ESX=$$CI_ESX_NAME
    commands:
      - misc/drone-scripts/validate-and-serialize.sh

  build_dev:
    image: cnastorage/vibauthor-and-go:0.9
    environment:
      - KEY=$$KEY
    commands:
      - pwd
      - go get github.com/golang/lint/golint
      - make -s build
      - echo $KEY | base64 -d > /drone/src/github.com/vmware/docker-volume-vsphere/key
      - chmod 0600 /drone/src/github.com/vmware/docker-volume-vsphere/key
    when:
      event: [push, pull_request]

  build_tag:
    image: cnastorage/vibauthor-and-go:0.9
    environment:
      - KEY=$$KEY
    commands:
      - export PKG_VERSION=$$TAG
      - echo $PKG_VERSION
      - go get github.com/golang/lint/golint
      - make -s build
      - echo $KEY | base64 -d > /drone/src/github.com/vmware/docker-volume-vsphere/key
      - chmod 0600 /drone/src/github.com/vmware/docker-volume-vsphere/key
    when:
      event: tag

  package_dev:
    image: cnastorage/fpm
    commands:
      - make -s deb rpm
    when:
      event: [push, pull_request]

  package_tag:
    image: cnastorage/fpm
    commands:
      - export PKG_VERSION=$$TAG
      - echo $PKG_VERSION
      - make -s deb rpm
    when:
      event: tag

  setup_pr_tag:
    image: cnastorage/vibauthor-and-go:0.9
    environment:
      - GOVC_USERNAME=$$CI_BASE_VMWARE_ESX_USER
      - GOVC_PASSWORD=$$CI_BASE_VMWARE_ESX_PASS
      - GOVC_INSECURE=1
      - GOVC_URL=$$CI_BASE_ESX_IP
      - TEST_ESX=$$CI_ESX_NAME
    commands:
      - misc/drone-scripts/setup.sh
    when:
      event: [pull_request, tag]

  setup_push:
    image: cnastorage/vibauthor-and-go:0.9
    environment:
      - GOVC_USERNAME=$$CI_BASE_VMWARE_ESX_USER
      - GOVC_PASSWORD=$$CI_BASE_VMWARE_ESX_PASS
      - GOVC_INSECURE=1
      - GOVC_URL=$$CI_BASE_ESX_IP
      - TEST_ESX=$$CI_ESX_NAME
    commands:
      - misc/drone-scripts/setup.sh
    when:
      event: [push]
      branch: [master, runci/*]

  test_dev_branch: # Identical to test except for when it occurs
    image: cnastorage/vibauthor-and-go:0.9
    privileged: true
    environment:
      - GOVC_USERNAME=$$CI_VMWARE_ESX_USER
      - GOVC_PASSWORD=$$CI_VMWARE_ESX_PASS
      - GOVC_INSECURE=1
      - GOVC_URL=$$CI_ESX_IP
      - SSH_KEY_OPT=-i /drone/src/github.com/vmware/docker-volume-vsphere/key
    commands:
      - pwd
      - export VM1=`govc vm.ip photon.ga.vmfs`
      - export VM2=`govc vm.ip Ubuntu.1404.vmfs`
      - ./misc/drone-scripts/deploy-and-test-wrapper.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null
      - echo
      - echo "=> Running tests on VSAN"
      - echo "=>" `date`
      - echo
      - export VM1=`govc vm.ip photon.ga.vsan`
      - export VM2=`govc vm.ip Ubuntu.1404.vsan`
      - ./misc/drone-scripts/deploy-and-test-wrapper.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null
    when:
      event: [push]
      branch: [master, runci/*]

  test: 
    image: cnastorage/vibauthor-and-go:0.9
    privileged: true
    environment:
      - GOVC_USERNAME=$$CI_VMWARE_ESX_USER
      - GOVC_PASSWORD=$$CI_VMWARE_ESX_PASS
      - GOVC_INSECURE=1
      - GOVC_URL=$$CI_ESX_IP
      - SSH_KEY_OPT=-i /drone/src/github.com/vmware/docker-volume-vsphere/key
    commands:
      - export VM1=`govc vm.ip photon.ga.vmfs`
      - export VM2=`govc vm.ip Ubuntu.1404.vmfs`
      - ./misc/drone-scripts/deploy-and-test-wrapper.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null
      - echo
      - echo "=> Running tests on VSAN"
      - echo "=>" `date`
      - echo
      - export VM1=`govc vm.ip photon.ga.vsan`
      - export VM2=`govc vm.ip Ubuntu.1404.vsan`
      - ./misc/drone-scripts/deploy-and-test-wrapper.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null
    when:
      event: [pull_request]

  test_tag: 
    image: cnastorage/vibauthor-and-go:0.9
    privileged: true
    environment:
      - GOVC_USERNAME=$$CI_VMWARE_ESX_USER
      - GOVC_PASSWORD=$$CI_VMWARE_ESX_PASS
      - GOVC_INSECURE=1
      - GOVC_URL=$$CI_ESX_IP
      - SSH_KEY_OPT=-i /drone/src/github.com/vmware/docker-volume-vsphere/key
    commands:
      - export PKG_VERSION=$$TAG
      - export VM1=`govc vm.ip photon.ga.vmfs`
      - export VM2=`govc vm.ip Ubuntu.1404.vmfs`
      - ./misc/drone-scripts/deploy-and-test-wrapper.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null
      - echo
      - echo "=> Running tests on VSAN"
      - echo "=>" `date`
      - echo
      - export VM1=`govc vm.ip photon.ga.vsan`
      - export VM2=`govc vm.ip Ubuntu.1404.vsan`
      - ./misc/drone-scripts/deploy-and-test-wrapper.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null
    when:
      event: [tag]


matrix:
  GO_VERSION:
    - 1.6

publish:
  github_release:
    api_key: $$GITHUB_TOKEN
    files:
      - build/*.deb
      - build/*.rpm
      - build/*.vib
      - build/*.zip
    when:
      event: tag
