# Dockerfile for 'go build' with docker plugin helpers preinstalled
# Dockerized golang info: https://github.com/docker-library/golang

FROM  golang:latest

MAINTAINER cna-storage@vmware.com

RUN go get github.com/docker/go-plugins-helpers/...
